### ISSUE TITLE
QT5 FreeCAD

### ISSUE THREAD

**Issue by asctime** [Neumann-A/my-vcpkg-ports#1]
It seems maybe [multiple issues](https://github.com/microsoft/vcpkg/issues/35260) around vcpkg QT6 (dependencies, tree depth limits, VC 19.37 compatibility to name a few..)

Is a QT5 version possible?

**Comment by Neumann-A** [comment]
The FreeCAD port in here is not really useable currently. I never got the time to finish it. I'll take a look at the Qt6 issue however since that is probably easy to solve.

**Comment by Neumann-A** [comment]
So got it running now: 

![image](https://github.com/Neumann-A/my-vcpkg-ports/assets/30894796/55aa487d-9769-4099-9393-4eda7b0723e3)


Just need to fix some ports to get there. (and patch freecad itself)
